[[tasks]]
name = "test_task_!"
description = "для тестирования системы копирования"
source_dir = "/hard/xar/medo_testdata/0"
target_dir = "/hard/xar/medo_testdata/out1"
report_dir = "/hard/xar/medo_testdata/sending_dir"
timer = 60000
delete_after_copy = false
copy_modifier = "CopyOnly"
is_active = true
clean_types = ["Квитанция"]
generate_exclude_file = false
color = "#0C660C"

[tasks.filters]
document_types = ["Транспортный пакет", "Документ"]
document_uids = []
