[[tasks]]
name = "from_backup_to_architector"
source_dir = "../test_data/in"
target_dir = "../test_data/out"
timer = 20000
delete_after_copy = false
copy_modifier = "CopyAll"
is_active = true
clean_types = []

[tasks.filters]
document_types = ["Транспортный контейнер", "Документ"]
document_uids = []

[[tasks]]
name = "from_in_to_backup"
source_dir = "../test_data/in2"
target_dir = "../test_data/out"
timer = 15000
delete_after_copy = false
copy_modifier = "CopyOnly"
is_active = true
clean_types = []

[tasks.filters]
document_types = ["Транспортный контейнер", "Документ"]
document_uids = []
