[[tasks]]
name = "from_backup_to_architector"
source_dir = "../test_data/in"
target_dir = "../test_data/out"
timer = 15000
delete_after_copy = false
is_active = true
clean_types = []
[tasks.filters]
document_types =  ["Транспортный контейнер","Документ"]
copy_modifier = "CopyAll"

[[tasks]]
name = "from_in_to_backup"
source_dir = "../test_data/in2"
target_dir = "../test_data/out"
timer = 12000
delete_after_copy = false
is_active = true
[tasks.filters]
document_types =  ["Транспортный контейнер","Документ"]
copy_modifier = "CopyOnly"