[[tasks]]
name = "from_backup_to_architector"
source_dir = "/hard/xar/projects/rust/copy_from_in/test_data/in"
target_dir = "/hard/xar/projects/rust/copy_from_in/test_data/out"
timer = 15000
delete_after_copy = false
is_active = true
document_types =  ["Транспортный контейнер","Документ"]
copy_modifier = "copy_all"

[[tasks]]
name = "from_in_to_backup"
source_dir = "/hard/xar/projects/rust/copy_from_in/test_data/in2"
target_dir = "/hard/xar/projects/rust/copy_from_in/test_data/out"
timer = 12000
delete_after_copy = false
is_active = true
document_types =  ["Транспортный контейнер","Документ"]
copy_modifier = "copy_only"