[[tasks]]
name = "from_backup_to_architector"
description = "задача копирования из бэкапа в архитектор"
source_dir = "test_data/in"
target_dir = "test_data/out"
report_dir = "test_data/report"
timer = 15000
delete_after_copy = false
copy_modifier = "CopyAll"
is_active = true
clean_types = ["Квитанция"]
generate_exclude_file = false
color = "#44FFE9"

[tasks.filters]
document_types = ["Транспортный контейнер", "Документ"]
document_uids = []

[[tasks]]
name = "from_in_to_backup"
description = ""
source_dir = "test_data/in2"
target_dir = "test_data/out"
report_dir = "test_data/report"
timer = 45000
delete_after_copy = false
copy_modifier = "CopyOnly"
is_active = true
clean_types = []
generate_exclude_file = false
color = "#7F44FF"

[tasks.filters]
document_types = ["Транспортный контейнер", "Документ"]
document_uids = []
