[[tasks]]
name = "from_backup_to_architector"
description = "задача копирования из бэкапа в архитектор"
source_dir = "test_data/in"
target_dir = "test_data/out"
report_dir = "test_data/report"
timer = 15000
delete_after_copy = false
copy_modifier = "CopyAll"
is_active = true
clean_types = ["Квитанция"]
generate_exclude_file = true
color = "#44FFE9"
sound = false
autocleaning = false
visible = true

[tasks.filters]
document_types = ["Транспортный контейнер", "Документ"]
document_uids = []

[[tasks]]
name = "from_in_to_backup"
description = "Копирование из деректории in в директорию backup"
source_dir = "test_data/in2"
target_dir = "test_data/out"
report_dir = "test_data/report"
timer = 45000
delete_after_copy = false
copy_modifier = "CopyOnly"
is_active = true
clean_types = ["Квитанция"]
generate_exclude_file = true
color = "#7F44FF"
sound = true
autocleaning = false
visible = true

[tasks.filters]
document_types = ["Транспортный контейнер", "Документ"]
document_uids = []

[[tasks]]
name = "test_in3_task"
description = "тестовая задача"
source_dir = "test_data/in3"
target_dir = "test_data/out"
report_dir = "test_data/report"
timer = 45000
delete_after_copy = false
copy_modifier = "CopyOnly"
is_active = true
clean_types = ["Квитанция"]
generate_exclude_file = true
color = "#E0D457"
sound = false
autocleaning = true
visible = true

[tasks.filters]
document_types = ["Документ", "Транспортный контейнер"]
document_uids = []
