import disease_ico from '../assets/svg/coronavirus.svg'
import disease_red_ico from '../assets/svg/coronavirus_red.svg'
import health_ico from '../assets/svg/health.svg'
import palm_ico from '../assets/svg/palm.svg'
import user_ico from '../assets/svg/edit_user_2.svg'
import vacc_ico from '../assets/svg/vacc.svg'
import test_ico from '../assets/svg/covid_test.svg'
import info_ico from '../assets/svg/info.svg'
import add_user_ico from '../assets/svg/add_user.svg'
import run_man_ico from '../assets/svg/runman.svg'
import train_ico from '../assets/svg/train.svg'
import journal_ico from '../assets/svg/journal.svg'
import bell_ico from '../assets/svg/bell.svg'
import error_ico from '../assets/svg/error.svg'
import envelope_ico from '../assets/svg/envelope.svg'
import clean_ico from '../assets/svg/clean.svg'
import cut_ico from '../assets/svg/cut.svg'
import background from '../assets/svg/back.svg'

export {disease_ico, background, health_ico, cut_ico, palm_ico, clean_ico, error_ico, envelope_ico, user_ico, test_ico, vacc_ico, info_ico, add_user_ico, run_man_ico, train_ico, disease_red_ico, journal_ico, bell_ico}